-- =============================================================================
-- Part 3.2  Star schema DDL
--   Grain of fact_encounters: ONE ROW PER ENCOUNTER  (Design Decision 1)
--   Convention: *_key = warehouse surrogate key (never exposed to source systems)
--               *_id  = source-system natural key (kept for traceability)
--   Convention: key = -1 is the "Unknown" member. Foreign keys are NEVER NULL.
--
-- Why never a NULL foreign key: a NULL silently drops the fact row from every
-- inner join, so bad data becomes invisible instead of loud. A -1 Unknown member
-- keeps the row countable: SELECT count(*) ... WHERE patient_key = -1.
-- =============================================================================
DROP SCHEMA IF EXISTS star CASCADE;
CREATE SCHEMA star;
SET search_path = star, public;

-- ---------------------------------------------------------------------------
-- dim_date : conformed date dimension. Loaded ONCE, never changes.
--            Smart key YYYYMMDD: human-readable in plans, sorts naturally.
--            Role-plays as admit date, discharge date and procedure date.
-- ---------------------------------------------------------------------------
CREATE TABLE dim_date (
    date_key      INT         PRIMARY KEY,      -- 20240510
    calendar_date DATE        NOT NULL UNIQUE,
    year          SMALLINT    NOT NULL,
    quarter       SMALLINT    NOT NULL,
    month         SMALLINT    NOT NULL,
    month_name    VARCHAR(9)  NOT NULL,
    year_month    CHAR(7)     NOT NULL,         -- '2024-05'  <- GROUP BY this
    day_of_month  SMALLINT    NOT NULL,
    day_of_week   SMALLINT    NOT NULL,         -- 1=Mon
    day_name      VARCHAR(9)  NOT NULL,
    week_of_year  SMALLINT    NOT NULL,
    is_weekend    BOOLEAN     NOT NULL
);
COMMENT ON TABLE dim_date IS 'Conformed calendar. Pre-computed parts remove per-row date functions from every query.';
CREATE INDEX idx_dim_date_ym   ON dim_date (year_month);
CREATE INDEX idx_dim_date_yr_m ON dim_date (year, month);

-- ---------------------------------------------------------------------------
-- dim_patient : SCD Type 1 (overwrite).
--   NOTE: no age_group here on purpose — age drifts, so an age band stored in
--   the dimension silently rewrites history on reload. age_at_encounter lives
--   on the fact instead, where it is correct forever. (Design Decision 2.)
-- ---------------------------------------------------------------------------
CREATE TABLE dim_patient (
    -- BY DEFAULT, not ALWAYS: GENERATED ALWAYS AS IDENTITY would REJECT the
    -- explicit `patient_key = -1` insert for the Unknown member. Real gotcha.
    patient_key   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id    INT UNIQUE,                   -- natural key from OLTP
    mrn           VARCHAR(20),
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    full_name     VARCHAR(201),                 -- denormalized: saves a concat per row
    date_of_birth DATE,
    gender        CHAR(1),
    load_ts       TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_patient IS 'One row per patient (SCD1). age_at_encounter deliberately lives on the fact.';

-- ---------------------------------------------------------------------------
-- dim_specialty : the shortcut dimension.
--   specialty_name is ALSO denormalized into dim_provider, so this table looks
--   redundant. It is not, and the redundancy is the entire point: the fact
--   carries specialty_key DIRECTLY, so Q1 and Q4 reach specialty in ONE hop
--   instead of walking encounters -> providers -> specialties. Storage is
--   traded for join depth, deliberately.
-- ---------------------------------------------------------------------------
CREATE TABLE dim_specialty (
    specialty_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_id   INT UNIQUE,                  -- natural key from OLTP
    specialty_name VARCHAR(100),
    specialty_code VARCHAR(10),
    load_ts        TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_specialty IS
  'Medical specialty. Referenced DIRECTLY from the fact so Q1/Q4 collapse a 2-hop chain (encounters->providers->specialties) into one hop.';

-- ---------------------------------------------------------------------------
-- dim_department : a physical unit in the hospital.
--   WHICH department does the fact reference? The ENCOUNTER's
--   (encounters.department_id), not the provider's. The two disagree ~10% of
--   the time in the source data, and they answer different questions:
--     - "where was this care delivered?"  -> encounter's department  -> FACT
--     - "which unit does this clinician report to?" -> provider's home
--       department -> carried on dim_provider instead.
--   Attributing an encounter to the provider's home unit would misreport
--   capacity/utilisation for the unit that actually hosted the visit.
-- ---------------------------------------------------------------------------
CREATE TABLE dim_department (
    department_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id   INT UNIQUE,                 -- natural key from OLTP
    department_name VARCHAR(100),
    floor           INT,
    capacity        INT,
    load_ts         TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_department IS
  'Hospital unit. The fact references the ENCOUNTER''s department (where care happened); the provider''s home department is denormalized onto dim_provider.';

-- ---------------------------------------------------------------------------
-- dim_provider : FLATTENED RATHER THAN SNOWFLAKED.
--   specialty_name and department_name are denormalized copies of values that
--   also live in dim_specialty / dim_department. That duplication is
--   intentional: it trades storage for one-hop reads, which is the whole
--   premise of a star schema. Snowflaking these back out would recreate the
--   join chain the OLTP model is being replaced for.
--   The surrogate keys are kept alongside the copies so a query can still join
--   out to the full dimension when it needs attributes not copied here.
-- ---------------------------------------------------------------------------
CREATE TABLE dim_provider (
    provider_key    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     INT UNIQUE,                 -- natural key from OLTP
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    full_name       VARCHAR(201),               -- denormalized: saves a concat per row
    credential      VARCHAR(20),
    specialty_key   INT REFERENCES dim_specialty(specialty_key),
    specialty_name  VARCHAR(100),               -- DENORMALIZED COPY. intentional.
    department_key  INT REFERENCES dim_department(department_key),
    department_name VARCHAR(100),               -- DENORMALIZED COPY. intentional.
    load_ts         TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_provider IS
  'Clinician. Flattened rather than snowflaked: specialty_name and department_name are denormalized copies, trading storage for one-hop reads.';

-- ---------------------------------------------------------------------------
-- dim_encounter_type : only 3 rows — why a whole dimension?
--   1. Conformance: 'ER' means the same thing in every fact table that uses it.
--   2. It carries ATTRIBUTES a bare string cannot: is_inpatient / is_emergency
--      let a query filter on meaning rather than on string equality, and new
--      attributes can be added without touching 600k fact rows.
--   3. Storage/scan cost: a 4-byte int on the fact instead of a VARCHAR(50)
--      repeated 600,000 times — a narrower fact means more rows per page.
--   Loaded from a CURATED list, not SELECT DISTINCT off the facts: sniffing
--   the fact table means 'ER' silently disappears from reports in any period
--   with no ER visits. Reference data should be declared, not inferred.
-- ---------------------------------------------------------------------------
CREATE TABLE dim_encounter_type (
    encounter_type_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name          VARCHAR(50) UNIQUE,
    is_inpatient       BOOLEAN NOT NULL DEFAULT FALSE,
    is_emergency       BOOLEAN NOT NULL DEFAULT FALSE,
    load_ts            TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_encounter_type IS
  'Curated list of encounter types. Justifies its existence via conformance + is_inpatient/is_emergency attributes + a 4-byte key instead of a 50-char string on every fact row.';

-- ---------------------------------------------------------------------------
-- dim_diagnosis / dim_procedure : the ICD-10 and CPT code books.
--   Reached through bridge tables, never directly from the fact — an encounter
--   has MANY of each, so a direct foreign key would force a finer grain.
-- ---------------------------------------------------------------------------
CREATE TABLE dim_diagnosis (
    diagnosis_key     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis_id      INT UNIQUE,               -- natural key from OLTP
    icd10_code        VARCHAR(10),
    icd10_description VARCHAR(200),
    load_ts           TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_diagnosis IS 'ICD-10 code book. Joined via bridge_encounter_diagnoses, never directly from the fact.';
CREATE INDEX idx_dim_diagnosis_code ON dim_diagnosis (icd10_code);

CREATE TABLE dim_procedure (
    procedure_key   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procedure_id    INT UNIQUE,                 -- natural key from OLTP
    cpt_code        VARCHAR(10),
    cpt_description VARCHAR(200),
    load_ts         TIMESTAMP DEFAULT now()
);
COMMENT ON TABLE dim_procedure IS 'CPT code book. Joined via bridge_encounter_procedures, never directly from the fact.';
CREATE INDEX idx_dim_procedure_code ON dim_procedure (cpt_code);

-- ===========================================================================
-- FACT TABLE
--   GRAIN: one row per encounter.  encounter_id is UNIQUE -> enforced grain.
--   All dimension foreign keys NOT NULL; unresolved lookups map to -1 (Unknown).
-- ===========================================================================
CREATE TABLE fact_encounters (
    encounter_sk          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- degenerate dimension: source id kept on the fact for drill-back
    encounter_id          INT NOT NULL UNIQUE,

    -- dimension foreign keys ---------------------------------------------
    -- admit/discharge are the SAME dim_date playing two roles (role-playing
    -- dimension). Aliased per use at query time.
    admit_date_key        INT NOT NULL REFERENCES dim_date(date_key),
    discharge_date_key    INT NOT NULL REFERENCES dim_date(date_key),
    patient_key           INT NOT NULL REFERENCES dim_patient(patient_key),
    provider_key          INT NOT NULL REFERENCES dim_provider(provider_key),
    -- specialty_key on the fact is the shortcut that kills Q1/Q4's join chain.
    -- It is reachable via dim_provider too; carrying it here is the deliberate
    -- redundancy that removes a hop from the two most common queries.
    specialty_key         INT NOT NULL REFERENCES dim_specialty(specialty_key),
    -- the ENCOUNTER's department (see dim_department comment), not the provider's
    department_key        INT NOT NULL REFERENCES dim_department(department_key),
    encounter_type_key    INT NOT NULL REFERENCES dim_encounter_type(encounter_type_key),

    -- measures ------------------------------------------------------------
    encounter_count       SMALLINT      NOT NULL DEFAULT 1,  -- always 1; makes
        -- SUM(encounter_count) work identically at every roll-up level
    diagnosis_count       SMALLINT      NOT NULL DEFAULT 0,
    procedure_count       SMALLINT      NOT NULL DEFAULT 0,

    -- Billing measures. UNBILLED IS STORED AS 0, NOT NULL.
    --   Rationale: these are additive measures, and 0 is the truthful additive
    --   identity — "this encounter contributed no revenue". NULL would make
    --   AVG() and any arithmetic silently skip the row instead of counting it.
    --   claim_count is what distinguishes the two cases that 0 would otherwise
    --   conflate: claim_count = 0 means "never billed / no payable claim",
    --   claim_count > 0 with total_allowed_amount = 0 means "billed, allowed
    --   nothing". Keeping both keeps the distinction queryable.
    --   NOTE: the ETL must apply the SAME claim_status filter as Q4 (Denied
    --   claims excluded), or the parity test fails — correctly.
    claim_count           SMALLINT      NOT NULL DEFAULT 0,
    total_claim_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_allowed_amount  NUMERIC(14,2) NOT NULL DEFAULT 0,

    length_of_stay_hours  NUMERIC(10,2),
    age_at_encounter      SMALLINT,

    -- pre-computed analytics ----------------------------------------------
    is_inpatient          BOOLEAN       NOT NULL DEFAULT FALSE,

    -- ⭐ The two highest-value columns in the schema. Q3's 30-day readmission
    -- question is a SELF-JOIN on 600k rows in the OLTP model; here the answer
    -- is already computed, so Q3 degenerates into a GROUP BY over a boolean.
    -- The cost of pre-computing: this is DERIVED data. If the clinical
    -- definition changes from 30 days to 45, this column must be RELOADED —
    -- you cannot fix it by editing a query. days_to_next_encounter is kept
    -- precisely so the 30-day threshold stays auditable (and re-derivable)
    -- without going back to the OLTP source.
    is_readmit_30d          BOOLEAN     NOT NULL DEFAULT FALSE,
    days_to_next_encounter  INT,        -- NULL = no subsequent encounter exists.
        -- NULL is meaningful HERE (unlike a foreign key): it is the honest
        -- representation of "no next visit", not a failed lookup.

    -- lineage --------------------------------------------------------------
    load_ts               TIMESTAMP     NOT NULL DEFAULT now(),

    -- exact-grain guard: a bug in the ETL that duplicates rows fails HERE,
    -- loudly, instead of silently doubling every number downstream.
    CONSTRAINT uq_fact_grain UNIQUE (encounter_id)
);
COMMENT ON TABLE fact_encounters IS
  'Grain: one row per encounter. Additive measures + pre-computed readmission flag.';

-- Indexes: one per foreign key used for filtering/grouping. In a star schema the
-- engine typically hashes the small dimensions and scans the fact once, so these
-- matter most for selective filters and for FK validation speed.
CREATE INDEX idx_fact_admit_date     ON fact_encounters (admit_date_key);
CREATE INDEX idx_fact_discharge_date ON fact_encounters (discharge_date_key);
CREATE INDEX idx_fact_patient        ON fact_encounters (patient_key);
CREATE INDEX idx_fact_provider       ON fact_encounters (provider_key);
CREATE INDEX idx_fact_specialty      ON fact_encounters (specialty_key);
CREATE INDEX idx_fact_department     ON fact_encounters (department_key);
CREATE INDEX idx_fact_enc_type       ON fact_encounters (encounter_type_key);

-- Composite index serving Q1 and Q4 directly (both group by month x specialty).
-- Trade-off, stated plainly: it costs write time on every load and ~15-20MB of
-- disk, and a full-table aggregation may well ignore it in favour of a seq scan.
-- It earns its place only on FILTERED slices ("Cardiology, 2024-Q3").
-- To measure the delta rather than assume it:
--     DROP INDEX star.idx_fact_date_specialty;  -- then re-run make sq1 / make sq4
CREATE INDEX idx_fact_date_specialty ON fact_encounters (admit_date_key, specialty_key);

-- Partial index on the readmission cohort: only ~12% of rows are inpatient, so
-- Q3's WHERE is_inpatient filter reads a much smaller structure.
CREATE INDEX idx_fact_inpatient ON fact_encounters (specialty_key)
    WHERE is_inpatient;

-- ===========================================================================
-- BRIDGE TABLES  — many-to-many, preserved rather than flattened
--
-- Why bridges instead of columns on the fact: flattening would mean
-- diagnosis_1 .. diagnosis_N columns — a repeating group that breaks the
-- moment a patient has N+1 diagnoses, and makes "find every encounter with
-- code I10" scan every column. Why not a finer grain instead: that is the fan
-- trap (Design Decision 1) — total_allowed_amount would be duplicated once per
-- diagnosis. The bridge keeps the fact additive AND confines the many-to-many
-- join to the only query that needs code-level detail (Q2). Q1/Q3/Q4 never
-- touch these tables. That containment is the actual win.
-- ===========================================================================

CREATE TABLE bridge_encounter_diagnoses (
    encounter_sk       BIGINT   NOT NULL REFERENCES fact_encounters(encounter_sk),
    diagnosis_key      INT      NOT NULL REFERENCES dim_diagnosis(diagnosis_key),
    diagnosis_sequence SMALLINT,                                  -- 1 = primary
    is_primary         BOOLEAN GENERATED ALWAYS AS (diagnosis_sequence = 1) STORED,
    -- Production upgrade (Kimball's weighted bridge), noted but not implemented:
    --   allocation_factor NUMERIC(6,5) = 1.0 / diagnosis_count
    -- would let revenue be split across an encounter's diagnoses WITHOUT
    -- double counting, making "revenue per diagnosis" answerable from this
    -- grain. Not built here because no listed query needs it.
    --
    -- PK choice: (encounter_sk, diagnosis_key). The same ICD-10 code recorded
    -- twice for one encounter is not a real clinical event, it is a data-entry
    -- error — so collapsing it is correct, and the PK surfaces it rather than
    -- hiding it. Contrast with the procedures bridge below: the choice differs
    -- because the semantics differ, not by accident.
    PRIMARY KEY (encounter_sk, diagnosis_key)
);
COMMENT ON TABLE bridge_encounter_diagnoses IS
  'Many-to-many encounter<->diagnosis. Keeps the fact additive; confines the M2M join to queries that need diagnosis detail.';
CREATE INDEX idx_bed_diagnosis ON bridge_encounter_diagnoses (diagnosis_key);

CREATE TABLE bridge_encounter_procedures (
    -- DIFFERENT KEY STRATEGY FROM THE DIAGNOSIS BRIDGE, on purpose.
    -- The same CPT code CAN legitimately occur twice in one encounter — two
    -- chest X-rays, two identical injections are real, billable, distinct
    -- events. A PK of (encounter_sk, procedure_key) would therefore be WRONG:
    -- ON CONFLICT DO NOTHING would silently swallow the second occurrence, and
    -- the bridge row count would no longer match fact.procedure_count (the
    -- Phase 8 bridge-consistency test exists to catch exactly that).
    -- So: a surrogate PK preserves every occurrence, and the source's own
    -- encounter_procedure_id is carried as a UNIQUE natural key — which is
    -- what makes the load idempotent (ON CONFLICT on a real identity rather
    -- than on a collapsed pair).
    bridge_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_procedure_id INT    NOT NULL UNIQUE,   -- natural key from OLTP
    encounter_sk           BIGINT NOT NULL REFERENCES fact_encounters(encounter_sk),
    procedure_key          INT    NOT NULL REFERENCES dim_procedure(procedure_key),
    procedure_date_key     INT    NOT NULL REFERENCES dim_date(date_key)  -- role-playing
);
COMMENT ON TABLE bridge_encounter_procedures IS
  'Many-to-many encounter<->procedure. Surrogate PK (not encounter+procedure) because the same CPT code can legitimately repeat within one encounter.';
CREATE INDEX idx_bep_encounter ON bridge_encounter_procedures (encounter_sk);
CREATE INDEX idx_bep_procedure ON bridge_encounter_procedures (procedure_key);
